---
AWSTemplateFormatVersion: "2010-09-09"
Description: Windows Jump Secret
Parameters:
  namespace:
    Type: String
  environment:
    Type: String
  KmsKey:
    Type: String

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Windows Jump Secret"
      Name: !Sub ${namespace}-windowsjump
      KmsKeyId: !Ref KmsKey
      GenerateSecretString:
        SecretStringTemplate:
          Fn::Sub: '{
            "users": [
            "manager",
            "mikel"
            ]
            }'
        GenerateStringKey: "Secret"
        PasswordLength: 14
        ExcludeCharacters: ""
        ExcludePunctuation: True
      Tags:
        - Key: namespace
          Value: !Ref namespace
        - Key: environment
          Value: !Ref environment
